export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const GET_SECTIONS_REQUEST = "GET_SECTIONS_REQUEST";
export const GET_SECTIONS_SUCCESS = "GET_SECTIONS_SUCCESS";
export const GET_SECTIONS_FAILURE = "GET_SECTIONS_FAILURE";

export const GET_SECTIONS_CATEGORIES_REQUEST =
  "GET_SECTIONS_CATEGORIES_REQUEST";
export const GET_SECTIONS_CATEGORIES_SUCCESS =
  "GET_SECTIONS_CATEGORIES_SUCCESS";
export const GET_SECTIONS_CATEGORIES_FAILURE =
  "GET_SECTIONS_CATEGORIES_FAILURE";

export const CREATE_SECTION_REQUEST = "CREATE_SECTION_REQUEST";
export const CREATE_SECTION_SUCCESS = "CREATE_SECTION_SUCCESS";
export const CREATE_SECTION_FAILURE = "CREATE_SECTION_FAILURE";

export const DELETE_SECTION_REQUEST = "DELETE_SECTION_REQUEST";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const DELETE_SECTION_FAILURE = "DELETE_SECTION_FAILURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";






export const frequencyConstants={
  GET_FREQUENCY_REQUEST:"GET_FREQUENCY_REQUEST",
  GET_FREQUENCY_SUCCESS:"GET_FREQUENCY_SUCCESS",
  GET_FREQUENCY_FAILURE:"GET_FREQUENCY_FAILURE",
}